### ISSUE TITLE
Q&A

### ISSUE THREAD

**Issue by xblocksys** [xblocksys/Documentation#1]
기술백서에 대하여 궁금한 점이 있으시면 이 곳에 질의를 남겨 주세요.

**Comment by xblocksys** [comment]
기술백서 영문 버전은 언제 나오나요?

**Comment by JaceYoungjunCho** [comment]
안녕하세요 질문을 남기는 항목에대해 테스트 진행하봅니다.

**Comment by xblocksys** [comment]
Duplicate of #abcdef
